export JAVA_HOME=/usr/local/jdk1.7.0_80
export HADOOP_INSTALL=/usr/local/hadoop 
export HADOOP_HOME=$HADOOP_INSTALL 
export HADOOP_MAPRED_HOME=$HADOOP_INSTALL  
export HADOOP_COMMON_HOME=$HADOOP_INSTALL  
export HADOOP_HDFS_HOME=$HADOOP_INSTALL
export HADOOP_CONF_DIR=$HADOOP_INSTALL/etc/hadoop   
export YARN_HOME=$HADOOP_INSTALL
export YARN_CONF_DIR=$HADOOP_INSTALL/etc/hadoop

export HBASE_HOME=/usr/local/hbase-1.1.2

export SCALA_HOME=/usr/local/scala-2.12.0

export SPARK_HOME=/usr/local/spark-1.5.1

export PATH=$PATH:$HADOOP_INSTALL/bin:$HADOOP_INSTALL/sbin:$HBASE_HOME/bin:$SPARK_HOME/bin:$SCALA_HOME/bin  
